ERP_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('erp_system.urls'))
]

erp_system/urls.py
from django.urls import path
from . import views

app_name="erp_system"

urlpatterns = [
    path('', views.login_page, name='login'), # Login page view
    path('index/', views.index, name='index'), # Home page view
    path('view_inventories/', views.view_inventories, name='view_inventories'), # Inventory records view
    path('<int:inventory_id>/edit_inventory/', views.edit_inventory, name='edit_inventory'), # Edit Inventory records view
    path('<int:inventory_id>/update_inventory/', views.update_inventory, name='update_inventory'), # Function to update Inventory records
    path('<int:inventory_id>/delete_inventory/', views.delete_inventory, name='delete_inventory'), # Function to delete Inventory records
    path('add_inventory/', views.add_inventory, name='add_inventory'), # Add/Insert new Inventory view
    path('view_users/', views.view_users, name='view_users'), # System user list view
    path('add_user/', views.add_user, name='add_user'), # Create new system user view
    path('<int:user_id>/edit_user/', views.edit_user, name='edit_user'), #TODO give front-end access to edit users. going to require access layers
    path('<int:user_id>/delete_user', views.delete_user, name='delete_user'), #TODO give front-end access to delete users. going to require access layers
    path('reg_user', views.reg_user, name='reg_user'), # Function to create a new system user
    path('auth_user', views.auth_user, name='auth_user'), # Function to authenticate user into the system
    path('reg_inventory', views.reg_inventory, name='reg_inventory') # Function to insert Inventory records

] 

config/models.py
from django.db import models

# Create your models here.

erp_system/models.py
from django.db import models

# Create your models here.

# Base (non-normalized) Inventory data table
class Inventory(models.Model):
    """Inventory objects that contains descriptions, price and other properties of stock"""
    id = models.AutoField(primary_key=True)
    sku = models.CharField(max_length=30, unique=True)
    category_1 = models.CharField(max_length=100)
    category_2 = models.CharField(max_length=100, blank=True)
    category_3 = models.CharField(max_length=100, blank=True)
    description = models.TextField(max_length=300, blank=True)
    attribute_1 = models.CharField(max_length=20,default="", blank=True)
    attribute_2 = models.CharField(max_length=20,default="", blank=True)
    attribute_3 = models.CharField(max_length=20,default="", blank=True)
    retail_price = models.FloatField(default=0.00)
    branch_price = models.FloatField(default=0.00)
    cost_price = models.FloatField(default=0.00)
    supplier_name = models.CharField(max_length=20,default="", blank=True)
    backorder_qty = models.IntegerField(default=0)
    stock_available = models.IntegerField(default=0)

reports/models.py
from django.db import models

# Create your models here.

config/views.py
from django.shortcuts import render

# Create your views here.

erp_system/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .models import Inventory
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
# Create your views here.

def login_page(request):
    """Return html rendered view for login page"""
    return render(request, 'auth/login.html')

def index(request):
    """Return html rendered view of Home page and Dashboard"""
    latest_inventory_list = Inventory.objects.order_by('id')
    context = {'latest_inventory_list':latest_inventory_list}
    return render(request, 'index.html', context)

def view_inventories(request):
    """Return html rendered view of Inventory list view with Inventory objects"""
    latest_inventory_list = Inventory.objects.order_by('id')
    context = {'latest_inventory_list':latest_inventory_list}
    return render(request, 'inventories/view_inventories.html', context)

def edit_inventory(request, inventory_id):
    """Return html rendered view of Edit Inventory page with Inventory objects"""
    inventory = get_object_or_404(Inventory, pk=inventory_id)
    return render(request, 'inventories/edit_inventory.html', {'inventory':inventory})

def update_inventory(request, inventory_id):
    """Function to update inventory depending on the request on the front end form. Redirect back to inventories view""" 
    inventory = get_object_or_404(Inventory, pk=inventory_id)
    inventory.sku = request.POST['sku']
    inventory.category_1 = request.POST['category_1']
    inventory.category_2 = request.POST['category_2']
    inventory.category_3 = request.POST['category_3']
    inventory.attribute_1 = request.POST['attribute_1']
    inventory.attribute_2 = request.POST['attribute_2']
    inventory.attribute_3 = request.POST['attribute_3']
    inventory.description = request.POST['description']
    inventory.retail_price = request.POST['retail_price']
    inventory.supplier_name = request.POST['supplier_name']
    inventory.backorder_qty = request.POST['backorder_qty']
    inventory.stock_available = request.POST['stock_available']
    inventory.save()
    return HttpResponseRedirect(
            reverse('erp_system:view_inventories')
        )
    
def delete_inventory(request, inventory_id):
    """Function to delete a selected inventory item"""
    inventory = get_object_or_404(Inventory, pk=inventory_id)
    inventory.delete()
    return HttpResponseRedirect(
            reverse('erp_system:view_inventories')
        )
    
def add_inventory(request): 
    """Return html rendered view of Inventory Add page"""
    return render(request, 'inventories/add_inventory.html')

def reg_inventory(request):
    """Function to register a new inventory record"""
    inventory = Inventory(
    sku = request.POST['sku'],
    category_1 = request.POST['category_1'],
    category_2 = request.POST['category_2'],
    category_3 = request.POST['category_3'],
    attribute_1 = request.POST['attribute_1'],
    attribute_2 = request.POST['attribute_2'],
    attribute_3 = request.POST['attribute_3'],
    description = request.POST['description'],
    retail_price = request.POST['retail_price'],
    supplier_name = request.POST['supplier_name'],
    backorder_qty = request.POST['backorder_qty'],
    stock_available = request.POST['stock_available'],
    )
    inventory.save()
    return HttpResponseRedirect(
        reverse('erp_system:view_inventories')
    )

def auth_user(request):
    """Function to authenticate user into index page from login page"""
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(username=username, password=password)
    if user is None:
        return HttpResponseRedirect(
            reverse('erp_system:login_page')
        )
    else:
        login(request,user)
        return HttpResponseRedirect(
            reverse('erp_system:index')
        )

def view_users(request):
    """Return html rendered view of list of Users"""
    latest_users_list = User.objects.order_by('id')
    context = {'latest_users_list':latest_users_list}
    return render(request, 'config/users.html', context)

def add_user(request):
    """Return html rendered view of User Add view"""
    return render(request, 'config/user_add.html')

def reg_user(request):
    """Function to register a new user into system"""
    username = request.POST['username']
    password = request.POST['password']
    user = User.objects.create_user(username=username, password=password)
    user.save()
    return HttpResponseRedirect(
        reverse('erp_system:view_users')
    )

def edit_user(request):
    pass

def delete_user(request):
    pass

reports/views.py
from django.shortcuts import render

# Create your views here.

erp_system/templates/config/user_add.html
<!DOCTYPE html>
<!-- Login page that submits information and sends to the "reg_user function" -->

<!-- Bootstrap CDN link -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

<!-- Div that carries the Create User form. Made to fit center of the screen -->
<div class="center-screen">
<h1> Create User </h1>
<p>Enter your details to create a new user in the system</p>

<!-- Create User Form -->
<form id="create_user" action="{% url 'erp_system:reg_user' %}" method="post">

    {% csrf_token %}

<!-- Form body with data inputs for posting request -->
    <table>
        <tr>
            <td>
                <label class="col-form-label" for="first_name">First Name</label>
            </td>
            <td>
                <input class="form-control" type="first_name" name="first_name">
            </td>
        </tr>
        <tr>
            <td>
                <label class="col-form-label" for="">Last Name</label>
            </td>
            <td>
                <input class="form-control" type="last_name" name="last_name">
            </td>
        </tr>
        <tr>
            <td>
                <label class="col-form-label" for="">Email</label>
            </td>
            <td>
                <input class="form-control" type="email" name="email">
            </td>
        </tr>
        <tr><td><br></td></tr>
        <tr>
            <td>
                <label class="col-form-label" for="username">Username</label>
            </td>
            <td>
                <input class="form-control" type="text" name="username" required>
            </td>
        </tr>
        <tr>
            <td>
                <label class="col-form-label" for="password">Password</label>
            </td>
            <td>
                <input class="form-control" type="password" name="password" required>
            </td>
        </tr>

    </table>


</form>
<br/>
<!-- Add a button to move back to the view users page -->
<a href="/view_users"><input class="btn btn-outline-primary" type="submit" value="Go Back"  /></a> 
<input class="btn btn-success" type="submit" value="Add User" for="create_user" />
</div>



<!-- CSS styling -->
<style>
    .center-screen {
        border: 1px solid;
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        padding: 10px;
      }
</style>

erp_system/templates/config/user_edit.html
<!--TODO : Add view and functionality to edit users from the db -->

erp_system/templates/config/users.html
{% extends "header.html" %}

{% block content %}

<!-- This page shows the list of users from the system on the front-end -->

<!-- TODO : ADD SEARCH FUNCTIONALITY -->


<h2> View Users</h2>

<!-- Button for access the Create User page -->
<br/>
<form id="add_user" action="{% url 'erp_system:add_user'%}">
    <input class="btn btn-success" type="submit" form="add_user" value="Create New User">
</form>
<br/>

<!-- Table to view all users list -->
<table class="table table-striped table-hover table-bordered">
    <caption>List of System Users</caption>
    <!-- Table Headers -->
    <thead>
    <tr class="table-dark">
        <td>ID</td>
        <td>USERNAME</td>
        <td>FIRST NAME</td>
        <td>LAST NAME</td>
        <td>EMAIL</td>
        <td>IS_STAFF</td>
        <td>IS_ACTIVE</td>
        <td>DATE_JOINED</td>
        <td colspan="2">ACTIONS</td>
    </tr>
    </thead>
    <tbody>
    <!-- Generate Table data with user data -->
    {% for user in latest_users_list %}
    <tr>
        <td>{{ forloop.counter }}</td>
        <td>{{ user.username }}</td>
        <td>{{ user.first_name }}</td>
        <td>{{ user.last_name }}</td>
        <td>{{ user.email }}</td>
        <td>{{ user.is_staff }}</td>
        <td>{{ user.is_active }}</td>
        <td>{{ user.date_joined }}</td>
        <td><a href="{% url 'erp_system:edit_user' user.id %}"><input class="btn btn-outline-success" type="submit" value="UPDATE" ></a></td>
        <td><a href="{% url 'erp_system:delete_user' user.id %}"><input class="btn btn-outline-danger" type="submit" value="DELETE" ></a></td>
    </tr>
    {% endfor %}
    </tbody>
</table>

{% endblock %} 


erp_system/templates/header.html
<!-- Header view across the whole system that containers site navigations -->

<!DOCTYPE html>

<head>
<!-- Bootstrap CDN link -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>

<body>
<!-- Navigation Bar with Nav Links -->
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <a class="navbar-brand" href="#">ERP SYSTEM</a>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="/index/">HOME</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/view_inventories/">INVENTORIES</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/view_users/">CONFIG</a>
          </li>
            
        </ul>
        <!-- LOGOUT - TODO requires better way of logging out sessions  -->
        <a align="right" class="nav-link" href="/">LOGOUT</a>
      </div>
      


</nav>
<hr>

{% block content %}
{% endblock %} 
</body>

<!-- CSS Styling -->
<style>
    body{
        padding: 10px;
        box-sizing: border-box;
    }
</style>

erp_system/templates/index.html
<!-- HOME PAGE / DASHBOARD -->
{% extends "header.html" %}

{% block content %}

<h3> DASHBOARD</h3>
<br/>
<!-- Check to see if user is authenticated and print username accordingly -->
{% if user.is_authenticated %}
    <p>Welcome, {{ user.username }}!</p>
{% else %}
    <p>Please log in.</p>
{% endif %}

<br/>

<!-- Dummy data -->
<h5>Today's Quote:</h5>
<pre>
    Simplicity requires a two-step process. 
    First, we must invest time and energy to discover what stirs us as human beings, 
    what makes our hearts sing, and what brings us joy. 
    Then, we must proceed to create the life that reflects the unique people we truly are. 
    This is the heart and soul of simplicity. Linda Breen Pierce, Choosing Simplicity
</pre>

<h5>Recent Events:</h5>

<!-- TODO add some graphs and tables to the dashboard -->

{% endblock %} 

erp_system/templates/inventories/add_inventory.html
<!-- Add Inventory Form to insert new inventory records to the DB -->

{% extends "header.html" %}

{% block content %}
<h1>Add Inventory</h1>

<!-- A simple form (in table format) for the user to input the changes they want on the inventory item -->
<form id="add_inventory" action="{% url 'erp_system:reg_inventory' %}" method='post'>
    {% csrf_token %}
    <table class="table table-bordered">
        <caption>Add Inventory Form</caption>

        <tr>
            <td class="table-dark">
                <label for="sku">SKU:</label>
            </td>
            <td>
                <input type="textbox" name="sku" id="sku" value="{{ inventory.sku }}">
            </td>
            <td colspan=4 class="table-dark"></td>
        </tr>
        <tr>
            <td class="table-dark">
                <label for="category_1">category_1:</label>
            </td>
            <td>
                <input type="textbox" name="category_1" id="category_1" value="{{ inventory.category_1 }}">
            </td>
            <td class="table-dark">
                <label for="category_2">category_2:</label>
            </td>
            <td>
                <input type="textbox" name="category_2" id="category_2" value="{{ inventory.category_2 }}">
            </td>
            <td class="table-dark">
                <label for="category_3">category_3:</label>
            </td>
            <td>
                <input type="textbox" name="category_3" id="category_3" value="{{ inventory.category_3 }}">               
            </td>
        </tr>

        <tr>
            <td class="table-dark">
                <label for="attribute_1">attribute_1:</label>
            </td>
            <td>
                <input type="textbox" name="attribute_1" id="attribute_1" value="{{ inventory.attribute_1 }}">
            </td>
            <td class="table-dark">
                <label for="attribute_2">attribute_2:</label>
            </td>
            <td>
                <input type="textbox" name="attribute_2" id="attribute_2" value="{{ inventory.attribute_2 }}">
            </td>
            <td class="table-dark">
                <label for="attribute_3">attribute_3:</label>
            </td>
            <td>
                <input type="textbox" name="attribute_3" id="attribute_3" value="{{ inventory.attribute_3 }}">
            </td>
        </tr>

        <tr>
            <td class="table-dark">
                <label for="description">description:</label>
            </td>
            <td>
                <textarea name="description" id="description">{{inventory.description}}</textarea>
            </td>
            <td colspan=4 class="table-dark"></td>
        </tr>

        <tr>
            <td class="table-dark">
                <label for="retail_price">retail_price:</label>
            </td>
            <td>
                <input type="textbox" name="retail_price" id="retail_price" value="{{ inventory.retail_price }}">
            </td>
                <td class="table-dark">
                    <label for="branch_price">branch_price:</label>
                </td>
                <td>
                    <input type="textbox" name="branch_price" id="branch_price" value="{{ inventory.branch_price }}">
                </td>
                <td class="table-dark">
                    <label for="cost_price">cost_price:</label>
                </td>
                <td>
                    <input type="textbox" name="cost_price" id="cost_price" value="{{ inventory.cost_price }}">
                </td>
        </tr>
        <tr>
            <td class="table-dark">
                <label for="supplier_name">supplier_name:</label>
            </td>
            <td>
                <input type="textbox" name="supplier_name" id="supplier_name" value="{{ inventory.supplier_name }}">
            </td>
            <td colspan=4 class="table-dark"></td>
        </tr>
        <tr>
            <td class="table-dark">
                <label for="backorder_qty">backorder_qty:</label>
            </td>
            <td>
                <input type="textbox" name="backorder_qty" id="backorder_qty" value="{{ inventory.backorder_qty }}">
            </td>
            <td colspan=4 class="table-dark"></td>
        </tr>
        <tr>
            <td class="table-dark">
                <label for="stock_available">stock_available:</label>
            </td>
            <td>
                <input type="textbox" name="stock_available" id="stock_available" value="{{ inventory.stock_available }}">
            </td>
            <td colspan=4 class="table-dark"></td>
        </tr>
            

            
                
            

        </td></tr>
        
    </table>
</form>

<form id="go_back" action="/view_inventories/"></form>

<!-- inputs linked to it's form. An extra button created for user to go back to the inventories view -->
<input class="btn btn-success" type="submit" value="Save" form="add_inventory" />
<input class="btn btn-outline-primary" type="submit" value="Go back" form="go_back" />
{% endblock %}

erp_system/templates/inventories/edit_inventory.html
<!-- A simple form (in table format) for the user to input the changes they want on the inventory item -->

{% extends "header.html" %}

{% block content %}
<h1>Edit Inventory</h1>

<!-- Edit Inventory Form -->
<form id="edit_inventory" action="{% url 'erp_system:update_inventory' inventory.id %}" method='post'>
    {% csrf_token %}
    <table class="table table-bordered">
        <caption>Edit Inventory Form</caption>

        <tr>
            <td class="table-dark">
                <label for="sku">SKU:</label>
            </td>
            <td>
                <input type="textbox" name="sku" id="sku" value="{{ inventory.sku }}">
            </td>
            <td colspan=4 class="table-dark"></td>
        </tr>
        <tr>
            <td class="table-dark">
                <label for="category_1">category_1:</label>
            </td>
            <td>
                <input type="textbox" name="category_1" id="category_1" value="{{ inventory.category_1 }}">
            </td>
            <td class="table-dark">
                <label for="category_2">category_2:</label>
            </td>
            <td>
                <input type="textbox" name="category_2" id="category_2" value="{{ inventory.category_2 }}">
            </td>
            <td class="table-dark">
                <label for="category_3">category_3:</label>
            </td>
            <td>
                <input type="textbox" name="category_3" id="category_3" value="{{ inventory.category_3 }}">               
            </td>
        </tr>

        <tr>
            <td class="table-dark">
                <label for="attribute_1">attribute_1:</label>
            </td>
            <td>
                <input type="textbox" name="attribute_1" id="attribute_1" value="{{ inventory.attribute_1 }}">
            </td>
            <td class="table-dark">
                <label for="attribute_2">attribute_2:</label>
            </td>
            <td>
                <input type="textbox" name="attribute_2" id="attribute_2" value="{{ inventory.attribute_2 }}">
            </td>
            <td class="table-dark">
                <label for="attribute_3">attribute_3:</label>
            </td>
            <td>
                <input type="textbox" name="attribute_3" id="attribute_3" value="{{ inventory.attribute_3 }}">
            </td>
        </tr>

        <tr>
            <td class="table-dark">
                <label for="description">description:</label>
            </td>
            <td>
                <textarea name="description" id="description">{{inventory.description}}</textarea>
            </td>
            <td colspan=4 class="table-dark"></td>
        </tr>

        <tr>
            <td class="table-dark">
                <label for="retail_price">retail_price:</label>
            </td>
            <td>
                <input type="textbox" name="retail_price" id="retail_price" value="{{ inventory.retail_price }}">
            </td>
                <td class="table-dark">
                    <label for="branch_price">branch_price:</label>
                </td>
                <td>
                    <input type="textbox" name="branch_price" id="branch_price" value="{{ inventory.branch_price }}">
                </td>
                <td class="table-dark">
                    <label for="cost_price">cost_price:</label>
                </td>
                <td>
                    <input type="textbox" name="cost_price" id="cost_price" value="{{ inventory.cost_price }}">
                </td>
        </tr>
        <tr>
            <td class="table-dark">
                <label for="supplier_name">supplier_name:</label>
            </td>
            <td>
                <input type="textbox" name="supplier_name" id="supplier_name" value="{{ inventory.supplier_name }}">
            </td>
            <td colspan=4 class="table-dark"></td>
        </tr>
        <tr>
            <td class="table-dark">
                <label for="backorder_qty">backorder_qty:</label>
            </td>
            <td>
                <input type="textbox" name="backorder_qty" id="backorder_qty" value="{{ inventory.backorder_qty }}">
            </td>
            <td colspan=4 class="table-dark"></td>
        </tr>
        <tr>
            <td class="table-dark">
                <label for="stock_available">stock_available:</label>
            </td>
            <td>
                <input type="textbox" name="stock_available" id="stock_available" value="{{ inventory.stock_available }}">
            </td>
            <td colspan=4 class="table-dark"></td>
        </tr>

        </td></tr>
        
    </table>
</form>

<form id="go_back" action="/view_inventories/"></form>

<!-- inputs linked to it's form. An extra button created for user to go back to the inventories view -->
<input class="btn btn-success" type="submit" value="Save" form="edit_inventory" />
<input class="btn btn-outline-primary" type="submit" value="Go back" form="go_back" />
{% endblock %}

erp_system/templates/inventories/view_inventories.html
<!-- Inventory Data Table View -->

{% extends "header.html" %}

{% block content %}

<!-- TODO : ADD SEARCH FUNCTIONALITY -->


<h2> View Inventories</h2>
<!-- Table to view inventory list -->

<br />
<form id="add_inventory" action="{% url 'erp_system:add_inventory'%}" method="post">
    {% csrf_token %}
    <input class="btn btn-success" type="submit" form="add_inventory" value="ADD INVENTORY">
</form>
<br />

<table class="table table-striped table-hover table-bordered">
    <caption>List of Inventory Records</caption>
    <!-- Table Headers -->
    <thead>
    <tr class="table-dark">
        <td>ID</td>
        <td>SKU</td>
        <td>CATEGORIES</td>
        <td>DESCRIPTION</td>
        <td>ATTRIBUTES</td>
        <td>R/PRICE</td>
        <td>B/PRICE</td>
        <td>C/PRICE</td>
        <td>SUPPLIER</td>
        <td>BACKORDER</td>
        <td>QTY</td>
        <td colspan="2">ACTIONS</td>
    </tr>
    </thead>
    <!-- Generate Table data with inventory data -->
    <tbody>
    {% for inventory in latest_inventory_list %}
    <tr>
        <td>{{ forloop.counter }}</td>
        <td>{{ inventory.sku }}</td>
        <td>{{ inventory.category_1 }} | {{ inventory.category_2 }} | {{ inventory.category_3 }}</td>
        <td>{{ inventory.description }}</td>
        <td>{{ inventory.attribute_1 }} | {{ inventory.attribute_2 }} | {{ inventory.attribute_3 }}</td>
        <td>R{{ inventory.retail_price }}</td>
        <td>R{{ inventory.branch_price }}</td>
        <td>R{{ inventory.cost_price }}</td>
        <td>{{ inventory.supplier_name }}</td>
        <td>{{ inventory.backorder_qty }}</td>
        <td>{{ inventory.stock_available }}</td>
        <td><a href="{% url 'erp_system:edit_inventory' inventory.id %}"><input class="btn btn-outline-success" type="submit" value="UPDATE" ></a></td>
        <td><a href="{% url 'erp_system:delete_inventory' inventory.id %}"><input class="btn btn-outline-danger" type="submit" value="DELETE" ></a></td>
    </tr>
    {% endfor %}
</tbody>
<tfoot>
</tfoot>
</table>

{% endblock %} 
